version: 2
updates:
  - package-ecosystem: pip
    directory: /packages/python
    schedule:
      interval: weekly
    open-pull-requests-limit: 5
    groups:
      python-minor-patch:
        update-types:
          - minor
          - patch

  - package-ecosystem: npm
    directory: /packages/node
    schedule:
      interval: weekly
    open-pull-requests-limit: 5
    groups:
      node-minor-patch:
        update-types:
          - minor
          - patch

  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
    open-pull-requests-limit: 5
    groups:
      actions-minor-patch:
        update-types:
          - minor
          - patch
